.github/workflows/pylint.yml

Changed the artifact to V4.
Closes #29

Fixed the Pylint Workflow

---

.github/workflows/pylint.yml

Removed making a report and used the --fail-under flag for the score 9

Changing the pylint workflow and removing making a report file

---

README.md
dashboard/README.md
database/README.md
pipeline/README.md
terraform/README.md

Added readmes to the root and to each folder.
Closes #20

Readme templates

---

database/apply_schema.sh
database/schema.sql

Completes the sql_schema so that it deletes any existing tables and makes new empty ones. Adds bash script to apply schema. 
Closes #41

Completes sql_schema and adds bash file

---

database/schema.sql

Changes schema so some primary keys are auto-generated

Edits SQL schema

---

pipeline/extract.py
pipeline/requirements.txt

Created extract script.
Closes #38

Rob extract

---

.github/workflows/pytest.yml
requirements.txt

Made the workflow file that checks if all pytest files are working correctly and if not, then it will not push
Closes #50.

Completed a Pytest Workflow file

---

terraform/ETL_pipeline.tf
terraform/daily_upload.tf
terraform/dashboard.tf
terraform/plant_reading.tf
terraform/variables.tf

Made a skeleton for all cloud resources on AWS that will be made using Terraform

Made a skeleton of using Terraform for all Cloud resources

---

pipeline/pipeline.py
pipeline/requirements.txt

Created pipeline script, just waiting on transform script to clean data.
Closes #27

Rob pipeline

---

pipeline/insert_test_data.py

Some of the code needed to insert test_data

Insert test data

---

database/schema.sql

Updated schema to match ERD
Closes #63

Updates schema to match new ERD

---

database/seed_data.sql
database/seed_database.sh

Fixes seed data

---

database/seed_database.sh

Fixes bash script
Completes #70

Fixes bash script for seeding database

---

pipeline/transform.py

ETL transform file complete
Closes #25

etl transform complete

---

database/seed_database.sh
pipeline/pipeline.py
pipeline/requirements.txt
pipeline/tests/test_extract.py
pipeline/tests/test_pipeline.py

Wrote some tests for pipeline, STILL IN WORK! 
Also changed bits of pipeline.py, making pull request so Aren can work on pipeline.py

Rob pipeline tests

---

pipeline/transform.py

A small fix to transform to align with the schema.

small fix to transform

---

pipeline/pipeline.py
pipeline/transform.py

Fixes pipeline and transform files.
Closes #82

Fixed pipeline and transform

---

sns_trigger_lambda/main.py
sns_trigger_lambda/requirements.txt

Makes the sql query to get last three readings that are out of range

Start of trigger lambda

---

pipeline/README.md
pipeline/pipeline.py
pipeline/requirements.txt
pipeline/tests/test_pipeline.py
pipeline/transform.py

I have changed SQLAlchemy to use pyodbc instead as it is a much more simple solution.
Closes #87 - Purge SQLAlchemy

Rob purge alchemy

---

database/apply_schema.sh
database/connect_to_db.sh
database/seed_data.sql
database/seed_database.sh

Adds -C to the bash files to fix connection to database to bypass certificate issues.
Closes #92

Changes bash script to include -C

---

dashboard/README.md
dashboard/dashboard.py
dashboard/requirements.txt

over Time with filters for the time period and plant id being selected.
This will also need some changes in the schema with a connection between plant and botanist for the filtering of all data by botanist as well which can be done later.

Made the dashboard for Temperature and Soil Moisture

---

.github/workflows/pipeline_image.yml
README.md

I have created a github action that:
- builds the pipeline image with the most recent code
- pushes the image to the ECR repository
Deleted placeholder file in the workflows folder.
Updated README to include required GitHub secrets.
Closes #96 - Implementing CI for the pipeline process.

Rob continuous integration

---

.github/workflows/pipeline_image.yml

Indented line 4, minor change.

image-build

---

sns_trigger_lambda/main.py

Changes connection type from sqlalchemy to pyodbc as we had issues with sqlalchemy when setting up lambdas on AWS.

Changes connection type

---

.github/workflows/pipeline_image.yml

Improving the CI workflow. Not sure it will pass but need to merge to find out.

Improving the CI github action

---

database/seed_data.sql

Fixes the insertion lines so the plants with ids 44 and 45 have their botanist ids.
Closes #119

Fixes typo for plant insertion for plant_ids 44 and 45

---

dashboard/dashboard.py

I have made the complete dashboard for the stakeholders to see which showcases the temperature and soil moisture results over different time periods like an hour or day.
The times are rolling averages of the last three minutes as well. 
Closes ticket #90 to create the dashboard

Making dashboard

---

.github/workflows/pipeline_image.yml
.github/workflows/plant_sns_image.yml

Added a workflow to auto deploy the sns alert image. This will allow easy updating of the lambda function.
Closes #122

Added a workflow to auto deploy the sns alert image

---

database/schema.sql

Change incident_at data type from timestamp to datetime because SQL Server sucks

Change incident_at data type

---

dashboard/Dockerfile
dashboard/requirements.txt

Made the Dockerfile that will make the Docker image that will work to create the ECS service for the dashboard to work in real time
Closes #128

Completed a Dockerfile for the dashboard

---

archive_lambda/main.py

The code that archives the records and incidents for all plants for the last 24 hours as parquet files to S3.
Closes #132 and #131

Archive lambda

---

dashboard/dashboard.py

Used caching for the connection thanks to st.cache_resource and also with getting the plant data and details with st.cache_data()
Closes #137

Made the dashboard load quicker with caching

---

sns_trigger_lambda/Dockerfile
sns_trigger_lambda/deploy_ses.sh
sns_trigger_lambda/main.py

Makes changes to files for the Dockerfile to work and also adds a bash file that deploys the image

Makes changes for Dockerfile

---

.gitignore

Update gitignore to include .coverage
Closes #143

Update gitignore to include .coverage

---

.github/ISSUE_TEMPLATE/bugs-issues-template.md
.github/workflows/archive_plant_data_image.yml
.github/workflows/dashboard_image.yml
.github/workflows/plant_sns_image.yml

Created a bug issue template for the project board for recording bugs.
Closes #146

Created a bug issue template for the project board

---

dashboard/dashboard.py

Completed work to fixing all Python code in the dashboard folder so that it scores 10/10 in Pylint

Completed fixing to the dashboard folder
